### ISSUE TITLE
Failed to activate the intentions package

### ISSUE THREAD

**Issue by cruzlauroiii** [steelbrain/intentions#51] opened 2017-03-30 05:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-dev-6a76ef5dd x64
**Electron**: 1.6.4
**OS**: Mac OS X 10.12.3
**Thrown From**: [intentions](https://github.com/steelbrain/intentions) package 1.1.2

### Stack Trace

Failed to activate the intentions package

```
At /Users/stellar/.atom/packages/intentions/lib/index.js: Buffer is not a constructor

TypeError: /Users/stellar/.atom/packages/intentions/lib/index.js: Buffer is not a constructor
    at Converter.toBase64 (/Applications/Atom.app/Contents/Resources/app/node_modules/convert-source-map/index.js:61:10)
    at Converter.toComment (/Applications/Atom.app/Contents/Resources/app/node_modules/convert-source-map/index.js:65:21)
    at File.generate (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:812:82)
    at File.transform (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:625:17)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/pipeline.js:168:19
    at File.wrap (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.exports.compile (/Applications/Atom.app/Contents/Resources/app/src/babel.js:70:1)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:68:1)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:97:1)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:229:1)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:56:1)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:810:1)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:211:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:194:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:100:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:187:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:184:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:557:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:538:1
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:533:1)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:515:1)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:874:1
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.3.0 
intentions 1.1.2 
lebab 0.10.0 
linter 2.1.2 
linter-eslint 8.1.4 
linter-ui-default 1.2.2 
```

**Comment by steelbrain** [comment] 2017-03-30 06:11
That's actually an internal Atom error, should be resolved with a restart

**Closed as completed by steelbrain** 2017-03-30 06:11 UTC

**Comment by cruzlauroiii** [comment] 2017-04-20 22:09
this is not an atom error as i compiled atom from git sources:

navigator.appVersion
"5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Atom/1.18.0-dev-1f3bb12a1 Chrome/56.0.2924.87 Electron/1.6.7 Safari/537.36"

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-dev-1f3bb12a1 x64
**Electron**: 1.6.7
**OS**: Mac OS X 10.12.5
**Thrown From**: [intentions](https://github.com/steelbrain/intentions) package 1.1.2


### Stack Trace

Failed to activate the intentions package

```
At /Users/stellar/.atom/packages/intentions/lib/index.js: Buffer is not a constructor

TypeError: /Users/stellar/.atom/packages/intentions/lib/index.js: Buffer is not a constructor
    at Converter.toBase64 (/Applications/Atom.app/Contents/Resources/app/node_modules/convert-source-map/index.js:61:10)
    at Converter.toComment (/Applications/Atom.app/Contents/Resources/app/node_modules/convert-source-map/index.js:65:21)
    at File.generate (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:812:82)
    at File.transform (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:625:17)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/pipeline.js:168:19
    at File.wrap (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.exports.compile (/Applications/Atom.app/Contents/Resources/app/src/babel.js:70:1)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:72:1)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:97:1)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:229:1)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:1)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:1)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:600:1)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:846:1
```

### Commands

```
     -1:49.8.0 window:toggle-dev-tools (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
intentions 1.1.2 
lebab 0.10.0 
linter 2.1.4 
linter-eslint 8.1.6 
linter-ui-default 1.2.3 
remove-whitespace 0.2.1 
symbol-gen 1.3.1 
```

**Comment by Arcanemagus** [comment] 2017-04-20 22:45
@cruzlauroiii You've now posted the same stack trace in two different projects and claimed that because you built it yourself from `master` it _must_ not be your Atom version, however _nobody_ else is getting this error and you are getting it on two different packages!

Are you able to reproduce this on stable or beta channels of Atom?

**Comment by Arcanemagus** [comment] 2017-04-20 22:50
@cruzlauroiii For some further details, your stack trace is pointing to [here](https://github.com/thlorenz/convert-source-map/blob/718588276a59377afd975419a39505c6a7d971ea/index.js#L61), which is being used internally in Atom, so something is broken in your build of it.
