### ISSUE TITLE
atom-ide-base disables intentions automatically 

### ISSUE THREAD

**Issue by rjousse18** [steelbrain/intentions#77] opened 2021-02-16 15:37 UTC
When I start atom, when I look in my packages, Intentions package is always disable even when i enable it and restart atom, it's again disable.

I tried to uninstall/install but no changes... Any idea ?

**Comment by Robertschv** [comment] 2021-03-23 00:08
I am having the same issue, it disables itself when I restart the Atom

the problem is "atom-ide-base" package, if you disable this and all their dependencies, Intentions should work fine again

**Comment by aminya** [comment] 2021-06-14 22:12
atom-ide-base disables intensions due to the bugs in the intensions package. We need to fix these bugs before making this package usable again.

**Comment by aminya** [comment] 2021-06-15 05:58
Fixed in atom-ide-base 3.1.0

**Closed as completed by aminya** 2021-06-15 05:58 UTC
